# MySQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-db
  labels:
    app: ecommerce
    tier: database
spec:
  replicas: 1  # MySQL running as single instance
  selector:
    matchLabels:
      app: ecommerce
      tier: database
  strategy:
    type: Recreate  # Ensures we don't run multiple MySQL pods trying to use same PVC
  template:
    metadata:
      labels:
        app: ecommerce
        tier: database
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root-credentials
              key: password
        - name: MYSQL_DATABASE
          value: "ecommerce"
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          exec:
            command: ["mysqladmin", "ping", "-h", "localhost", "-u", "subbu", "-padmin@1234"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe:
          exec:
            command: ["mysql", "-h", "localhost", "-u", "subbu", "-padmin@1234", "-e", "SELECT 1"]
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: mysql-initdb
        configMap:
          name: mysql-initdb-config