apiVersion: v1
kind: Service
metadata:
  name: ecommerce-db
  labels:
    app: ecommerce
    tier: database
spec:
  selector:
    app: ecommerce
    tier: database
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  type: ClusterIP